export const countires = [
  { name: 'Anguilla'},
  { name: 'Antigua And Barbuda'},
  { name: 'Argentina'},
  { name: 'Aruba'},
  { name: 'Barbados'},
  { name: 'Belize'},
  { name: 'Bolivia'},
  { name: 'Bonaire'},
  { name: 'Brazil'},
  { name: 'Cayman Island'},
  { name: 'Chile'},
  { name: 'Colombia'},
  { name: 'Costa Rica'},
  { name: 'Cuba'},
  { name: 'Curaçao'},
  { name: 'Dominica'},
  { name: 'Dominican Republic'},
  { name: 'Ecuador'},
  { name: 'El Salvador'},
  { name: 'Falkland Islands'},
  { name: 'French Guiana'},
  { name: 'Grenada'},
  { name: 'Guadeloupe'},
  { name: 'Guatemala'},
  { name: 'Guyana'},
  { name: 'Haiti'},
  { name: 'Honduras'},
  { name: 'Jamaica'},
  { name: 'Martinique'},
  { name: 'Mexico'},
  { name: 'Montserrat'},
  { name: 'Nicaragua'},
  { name: 'Panama'},
  { name: 'Paraguay'},
  { name: 'Peru'},
  { name: 'Puerto Rico'},
  { name: 'Saint Kitts And Nevis'},
  { name: 'Saint Lucia'},
  { name: 'Saint Vincent and the Grenadines'},
  { name: 'Saint-Barthelemy'},
  { name: 'Santiago'},
  { name: 'Sint Maarten (Dutch)'},
  { name: 'St. Eustatius & Saba'},
  { name: 'Suriname'},
  { name: 'The Bahamas'},
  { name: 'Trinidad And Tobago'},
  { name: 'Turks And Caicos Islands'},
  { name: 'Uruguay'},
  { name: 'Venezuela'},
  { name: 'Virgin Islands (British)'},
  { name: 'Virgin Islands (US)'},
  { name: 'Afghanistan'},
  { name: 'Australia'},
  { name: 'Bangladesh'},
  { name: 'Bhutan'},
  { name: 'Brunei'},
  { name: 'Cambodia'},
  { name: 'China'},
  { name: 'New Caledonia'},
  { name: 'India'},
  { name: 'Indonesia'},
  { name: 'Japan'},
  { name: 'Kiribati'},
  { name: 'Laos'},
  { name: 'Malaysia'},
  { name: 'Maldives'},
  { name: 'Marshall Islands'},
  { name: 'Micronesia'},
  { name: 'Mongolia'},
  { name: 'Nepal'},
  { name: 'New Zealand'},
  { name: 'Niue'},
  { name: 'North Korea'},
  { name: 'Pakistan'},
  { name: 'Palau'},
  { name: 'Papua New Guinea'},
  { name: 'Philippines'},
  { name: 'Singapore'},
  { name: 'Solomon Islands'},
  { name: 'South Korea'},
  { name: 'Sri Lanka'},
  { name: 'Taiwan'},
  { name: 'Thailand'},
  { name: 'Tonga'},
  { name: 'Tuvalu'},
  { name: 'Vanuatu'},
  { name: 'Vietnam'},
  { name: 'Cook Island'},
  { name: 'East Timor'},
  { name: 'Fiji Islands'},
  { name: 'Hong Kong S.A.R.'},
  { name: 'Macau S.A.R.'},
  { name: 'Myanmar'},
  { name: 'American Samoa'},
  { name: 'Armenia'},
  { name: 'Christmas Island'},
  { name: 'Cocos (Keeling) Islands'},
  { name: 'Norfolk Island'},
  { name: 'Azerbaijan'},
  { name: 'British Indian Ocean Territory'},
  { name: 'French Polynesia'},
  { name: 'Wallis And Futuna Islands'},
  { name: 'Georgia (Country)'},
  { name: 'Guam'},
  { name: 'Kazakhstan'},
  { name: 'Kyrgyzstan'},
  { name: 'Nauru'},
  { name: 'Northern Mariana Islands'},
  { name: 'Pitcairn Island'},
  { name: 'Russia'},
  { name: 'Samoa'},
  { name: 'Tajikistan'},
  { name: 'Tokelau'},
  { name: 'Turkmenistan'},
  { name: 'Uzbekistan'},
  { name: 'Bermuda'},
  { name: 'Canada'},
  { name: 'Alberta'},
  { name: 'British Columbia'},
  { name: 'Manitoba'},
  { name: 'New Brunswick'},
  { name: 'Nunavut'},
  { name: 'Saskatchewan'},
  { name: 'Newfoundland and Labrador'},
  { name: 'Ontario'},
  { name: 'Quebec'},
  { name: 'Nova Scotia'},
  { name: 'Prince Edward Island'},
  { name: 'Saint Pierre and Miquelon'},
  { name: 'United States'},
  { name: 'Alabama'},
  { name: 'Alaska'},
  { name: 'Arizona'},
  { name: 'Arkansas'},
  { name: 'California'},
  { name: 'Colorado'},
  { name: 'Connecticut'},
  { name: 'Delaware'},
  { name: 'Florida'},
  { name: 'Georgia (State)'},
  { name: 'Hawaii'},
  { name: 'Idaho'},
  { name: 'Illinois'},
  { name: 'Indiana'},
  { name: 'Iowa'},
  { name: 'Kansas'},
  { name: 'Kentucky'},
  { name: 'Louisiana'},
  { name: 'Maine'},
  { name: 'Maryland'},
  { name: 'Massachusetts'},
  { name: 'Michigan'},
  { name: 'Minnesota'},
  { name: 'Mississippi'},
  { name: 'Missouri'},
  { name: 'Montana'},
  { name: 'Nebraska'},
  { name: 'Nevada'},
  { name: 'New Hampshire'},
  { name: 'New Jersey'},
  { name: 'New Mexico'},
  { name: 'New York'},
  { name: 'North Carolina'},
  { name: 'North Dakota'},
  { name: 'Ohio'},
  { name: 'Oklahoma'},
  { name: 'Oregon'},
  { name: 'Pennsylvania'},
  { name: 'Rhode Island'},
  { name: 'South Carolina'},
  { name: 'South Dakota'},
  { name: 'Tennessee'},
  { name: 'Texas'},
  { name: 'Utah'},
  { name: 'Vermont'},
  { name: 'Virginia'},
  { name: 'Washington'},
  { name: 'West Virginia'},
  { name: 'Wisconsin'},
  { name: 'Wyoming'},
  { name: 'District of Columbia'},
  { name: 'United States Minor Outlying Islands'},
  { name: 'Albania'},
  { name: 'Andorra'},
  { name: 'Austria'},
  { name: 'Belarus'},
  { name: 'Belgium'},
  { name: 'Bosnia and Herzegovina'},
  { name: 'Bulgaria'},
  { name: 'Croatia'},
  { name: 'Cyprus'},
  { name: 'Czech Republic'},
  { name: 'Denmark'},
  { name: 'Greenland'},
  { name: 'Estonia'},
  { name: 'Faroe Islands'},
  { name: 'Finland'},
  { name: 'Aland Island'},
  { name: 'France'},
  { name: 'Saint-Martin (French)'},
  { name: 'Germany'},
  { name: 'Gibraltar'},
  { name: 'Greece'},
  { name: 'Guernsey and Alderney'},
  { name: 'Hungary'},
  { name: 'Iceland'},
  { name: 'Ireland'},
  { name: 'Italy'},
  { name: 'Jersey'},
  { name: 'Kosovo'},
  { name: 'Latvia'},
  { name: 'Liechtenstein'},
  { name: 'Lithuania'},
  { name: 'Luxembourg'},
  { name: 'Macedonia'},
  { name: 'Malta'},
  { name: 'Isle of Man'},
  { name: 'Moldova'},
  { name: 'Monaco'},
  { name: 'Montenegro'},
  { name: 'Netherlands'},
  { name: 'Norway'},
  { name: 'Svalbard And Jan Mayen Islands'},
  { name: 'Poland'},
  { name: 'Portugal'},
  { name: 'Romania'},
  { name: 'San Marino'},
  { name: 'Serbia'},
  { name: 'Slovakia'},
  { name: 'Slovenia'},
  { name: 'Spain'},
  { name: 'Sweden'},
  { name: 'Switzerland'},
  { name: 'Ukraine'},
  { name: 'United Kingdom'},
  { name: 'Vatican City State (Holy See)'},
  { name: 'Algeria'},
  { name: 'Angola'},
  { name: 'Benin'},
  { name: 'Botswana'},
  { name: 'Burkina Faso'},
  { name: 'Burundi'},
  { name: 'Cameroon'},
  { name: 'Cape Verde'},
  { name: 'Central African Republic'},
  { name: 'Chad'},
  { name: 'Comoros'},
  { name: 'Congo (Republic of Congo)'},
  { name: "Cote D'Ivoire (Ivory Coast)"},
  { name: 'Democratic Republic of the Congo'},
  { name: 'Djibouti'},
  { name: 'Equatorial Guinea'},
  { name: 'Eritrea'},
  { name: 'Ethiopia'},
  { name: 'Mayotte'},
  { name: 'Reunion'},
  { name: 'Gabon'},
  { name: 'Gambia'},
  { name: 'Ghana'},
  { name: 'Guinea'},
  { name: 'Guinea-Bissau'},
  { name: 'Kenya'},
  { name: 'Lesotho'},
  { name: 'Liberia'},
  { name: 'Libya'},
  { name: 'Madagascar'},
  { name: 'Malawi'},
  { name: 'Mali'},
  { name: 'Mauritania'},
  { name: 'Mauritius'},
  { name: 'Morocco'},
  { name: 'Mozambique'},
  { name: 'Namibia'},
  { name: 'Niger'},
  { name: 'Nigeria'},
  { name: 'Rwanda'},
  { name: 'Saint Helena'},
  { name: 'Sao Tome and Principe'},
  { name: 'Senegal'},
  { name: 'Seychelles'},
  { name: 'Sierra Leone'},
  { name: 'Somalia'},
  { name: 'South Africa'},
  { name: 'South Sudan'},
  { name: 'Sudan'},
  { name: 'Swaziland (Eswatini)'},
  { name: 'Tanzania'},
  { name: 'Togo'},
  { name: 'Tunisia'},
  { name: 'Uganda'},
  { name: 'Western Sahara'},
  { name: 'Zambia'},
  { name: 'Zimbabwe'},
  { name: 'Bahrain'},
  { name: 'Egypt'},
  { name: 'Iran'},
  { name: 'Iraq'},
  { name: 'Israel'},
  { name: 'Jordan'},
  { name: 'Kuwait'},
  { name: 'Lebanon'},
  { name: 'Oman'},
  { name: 'State of Palestine'},
  { name: 'Qatar'},
  { name: 'Saudi Arabia'},
  { name: 'Syria'},
  { name: 'Turkey'},
  { name: 'United Arab Emirates'},
  { name: 'Dubai'},
  { name: 'Yemen'},
  { name: 'Antarctica'},
  { name: 'Bouvet Island'},
  { name: 'French Southern Territories'},
  { name: 'Heard Island and McDonald Islands'},
  { name: 'South Georgia'},
  { name: 'International' }
]

export const regions = [
    { name: 'LATAM'},
    { name: 'APAC'},
    { name: 'North America'},
    { name: 'Europe'},
    { name: 'Africa'},
    { name: 'Middle East'},
    { name: 'Antarctica'},
    { name: 'Global'},
]

export const formats = [
    { name: 'CSV'},
    { name: 'DOC'},
    { name: 'DOCX'},
    { name: 'GIF'},
    { name: 'HTML'},
    { name: 'JPG'},
    { name: 'JSON'},
    { name: 'ODS'},
    { name: 'PDF'},
    { name: 'PNG'},
    { name: 'TXT'},
    { name: 'XLS'},
    { name: 'XLSX'},
    { name: 'XML'},
    { name: 'ZIP'},
]

export const languages = [
    { name: "Afrikaans"},
    { name: "Albanian"},
    { name: "Amharic"},
    { name: "Arabic"},
    { name: "Armenian"},
    { name: "Assamese"},
    { name: "Aymara"},
    { name: "Azerbaijani"},
    { name: "Bhojpuri"},
    { name: "Basque"},
    { name: "Belarusian"},
    { name: "Bengali"},
    { name: "Bambara"},
    { name: "Bosnian"},
    { name: "Bulgarian"},
    { name: "Burmese (Myanmar)"},
    { name: "Catalan"},
    { name: "Cebuano"},
    { name: "Chewa (Chichewa)"},
    { name: "Chinese (Simplified)"},
    { name: "Chinese (Traditional)"},
    { name: "Corsican"},
    { name: "Croatian"},
    { name: "Czech"},
    { name: "Danish"},
    { name: "Dogri"},
    { name: "Dutch"},
    { name: "English"},
    { name: "Esperanto"},
    { name: "Estonian"},
    { name: "Ewe"},
    { name: "Finnish"},
    { name: "French"},
    { name: "Galician"},
    { name: "Georgian"},
    { name: "German"},
    { name: "Greek"},
    { name: "Guarani"},
    { name: "Gujarati"},
    { name: "Haitian Creole"},
    { name: "Hausa"},
    { name: "Hawaiian"},
    { name: "Hebrew"},
    { name: "Hindi"},
    { name: "Hmong"},
    { name: "Hungarian"},
    { name: "Icelandic"},
    { name: "Igbo"},
    { name: "Ilocano"},
    { name: "Indonesian"},
    { name: "Irish"},
    { name: "Italian"},
    { name: "Japanese"},
    { name: "Javanese"},
    { name: "Kannada"},
    { name: "Kazakh"},
    { name: "Khmer"},
    { name: "Kinyarwanda"},
    { name: "Konkani"},
    { name: "Korean"},
    { name: "Krio"},
    { name: "Kurdish (Kurmanji)"},
    { name: "Kurdish (Sorani)"},
    { name: "Kyrgyz"},
    { name: "Lao"},
    { name: "Latin"},
    { name: "Latvian"},
    { name: "Lingala"},
    { name: "Lithuanian"},
    { name: "Luganda"},
    { name: "Luxembourgish"},
    { name: "Macedonian"},
    { name: "Maithili"},
    { name: "Malagasy"},
    { name: "Malay"},
    { name: "Malayalam"},
    { name: "Maldivian (Dhivehi)"},
    { name: "Maltese"},
    { name: "Māori (Maori)"},
    { name: "Marathi"},
    { name: "Meitei (Manipuri, Meiteilon)"},
    { name: "Mizo"},
    { name: "Mongolian"},
    { name: "Nepali"},
    { name: "Northern Sotho (Sepedi)"},
    { name: "Norwegian (Bokmål)"},
    { name: "Odia (Oriya)"},
    { name: "Oromo"},
    { name: "Pashto"},
    { name: "Persian"},
    { name: "Polish"},
    { name: "Portuguese"},
    { name: "Punjabi (Gurmukhi)"},
    { name: "Quechua"},
    { name: "Romanian"},
    { name: "Russian"},
    { name: "Samoan"},
    { name: "Sanskrit"},
    { name: "Scottish Gaelic (Scots Gaelic)"},
    { name: "Serbian"},
    { name: "Shona"},
    { name: "Sindhi"},
    { name: "Sinhala"},
    { name: "Slovak"},
    { name: "Slovenian"},
    { name: "Somali"},
    { name: "Sotho (Sesotho)"},
    { name: "Spanish"},
    { name: "Sundanese"},
    { name: "Swahili"},
    { name: "Swedish"},
    { name: "Tagalog (Filipino)"},
    { name: "Tajik"},
    { name: "Tamil"},
    { name: "Tatar"},
    { name: "Telugu"},
    { name: "Thai"},
    { name: "Tigrinya"},
    { name: "Tsonga"},
    { name: "Turkish"},
    { name: "Turkmen"},
    { name: "Twi"},
    { name: "Ukrainian"},
    { name: "Urdu"},
    { name: "Uyghur"},
    { name: "Uzbek"},
    { name: "Vietnamese"},
    { name: "Welsh"},
    { name: "West Frisian (Frisian)"},
    { name: "Xhosa"},
    { name: "Yiddish"},
    { name: "Yoruba"},
    { name: "Zulu"}
]

export const source_types = [
    { name: 'Un-Official' },
    { name: 'Official' },
]

export const coverages = [
    { name: 'Incomplete' },
    { name: 'Complete' },
]

export const types = [
    { name: 'Dump' },
    { name: 'Portal' },
    { name: 'API' },
]

export const costs = [
    { name: 'Free' },
    { name: 'Paid' },
]